name: First task
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install ci
      - name: run lint
        run: npm run lint
      - name: run tests
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: echo "Deploying"
