name: First task
on: push
jobs:
  testanddeploy:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install ci
      - name: run run lint
        run: npm lint
      - name: run tests
        run: npm run test
      - name: deploy
        run: echo "Deploying"
