name: Check Environment Variables
on:
  push:
    branches:
      - master
env:
  DB_URL: 'mydb-url:5000'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DB_URL: 'mydb-url:8080'
    steps:
      - name: check job environment
        run: |
          echo "DB URL: $DB_URL"
          echo "DB URL: ${{ env.DB_URL }}"
      - name: lint
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install ci
      - name: run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install ci
      - name: run tests
        run: npm run test
  checkEnv:
    runs-on: ubuntu-latest
    steps:
      - name: check URL
        run: echo "${{ env.DB_URL }}"
  checkSecrets:
    runs-on: ubuntu-latest
    steps:
      - name: check Secret
        run: |
          echo "ARTIFACT NAME: ${{ secrets.ARTIFACTNAME }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: echo "Deploying"
