name: Check Environments
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    environment: PRD
    env:
      DB_URL: $DBURL
    steps:
      - name: check PRD environment
        run: |
          echo "DB URL: $DB_URL"
          echo "DB URL: ${{ env.DB_URL }}"
          echo "ARTIFACT NAME: ${{ secrets.ARTIFCATNAME }}"
      - name: lint
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install ci
      - name: run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install ci
      - name: run tests
        run: npm run test
      - name: check DEV environment
        run: |
          echo "DB URL: $DB_URL"
          echo "DB URL: ${{ env.DB_URL }}"
          echo "ARTIFACT NAME: ${{ secrets.ARTIFCATNAME }}"
  checkEnv:
    runs-on: ubuntu-latest
    steps:
      - name: check GENERAL Environment
        run: echo "${{ env.DB_URL }}"
  checkSecrets:
    runs-on: ubuntu-latest
    steps:
      - name: check General Secret
        run: |
          echo "ARTIFACT NAME: ${{ secrets.ARTIFCATNAME }}"
          echo "ARTIFACT NAME: ${{ env.ARTIFACT_NAME }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: echo "Deploying"
